<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />

    <!-- Levanta la app real en memoria. -->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <!-- Simula Open-Meteo: latencia, 500s, timeouts. Con esto probamos el breaker. -->
    <PackageReference Include="WireMock.Net" />
    <!-- SQLite in-memory como DB de tests (relacional de verdad, no el provider InMemory). -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeatherService.Api\WeatherService.Api.csproj" />
  </ItemGroup>

</Project>
