// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherService.Infrastructure.Persistence;

#nullable disable

namespace WeatherService.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresWeatherDbContext))]
    partial class PostgresWeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("ForecastSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("MinTemperatureC")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ForecastSnapshotId", "Date")
                        .IsUnique();

                    b.ToTable("forecast_days", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationKey", "RetrievedAtUtc")
                        .HasDatabaseName("ix_forecast_snapshots_location_key_retrieved_at");

                    b.ToTable("forecast_snapshots", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.HasOne("WeatherService.Infrastructure.Persistence.ForecastSnapshot", null)
                        .WithMany("Days")
                        .HasForeignKey("ForecastSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
