// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherService.Infrastructure.Persistence;

#nullable disable

namespace WeatherService.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresWeatherDbContext))]
    partial class PostgresWeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("condition");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("ForecastSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("forecast_snapshot_id");

                    b.Property<double>("MaxTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("max_temperature_c");

                    b.Property<double>("MinTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("min_temperature_c");

                    b.HasKey("Id")
                        .HasName("pk_forecast_days");

                    b.HasIndex("ForecastSnapshotId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_forecast_days_forecast_snapshot_id_date");

                    b.ToTable("forecast_days", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("location_key");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location_name");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_forecast_snapshots");

                    b.HasIndex("LocationKey", "RetrievedAtUtc")
                        .HasDatabaseName("ix_forecast_snapshots_location_key_retrieved_at");

                    b.ToTable("forecast_snapshots", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.HasOne("WeatherService.Infrastructure.Persistence.ForecastSnapshot", null)
                        .WithMany("Days")
                        .HasForeignKey("ForecastSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecast_days_forecast_snapshots_forecast_snapshot_id");
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
