// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherService.Infrastructure.Persistence;

#nullable disable

namespace WeatherService.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteWeatherDbContext))]
    [Migration("20260908024634_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ForecastSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<double>("MinTemperatureC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ForecastSnapshotId", "Date")
                        .IsUnique();

                    b.ToTable("forecast_days", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationKey", "RetrievedAtUtc")
                        .HasDatabaseName("ix_forecast_snapshots_location_key_retrieved_at");

                    b.ToTable("forecast_snapshots", (string)null);
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastDay", b =>
                {
                    b.HasOne("WeatherService.Infrastructure.Persistence.ForecastSnapshot", null)
                        .WithMany("Days")
                        .HasForeignKey("ForecastSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherService.Infrastructure.Persistence.ForecastSnapshot", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
